name: clyps-api
region: nyc

services:
  - name: api
    github:
      repo: Dazzlin00/clyps
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 81
    instance_size_slug: basic-xxs
    instance_count: 1
    health_check:
      http_path: /health
      initial_delay_seconds: 40
      period_seconds: 30
      timeout_seconds: 5
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: PORT
        value: "4000"
        scope: RUN_AND_BUILD_TIME
      - key: DB_HOST
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_PORT
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_USERNAME
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_PASSWORD
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_DATABASE
        scope: RUN_AND_BUILD_TIME
        type: SECRET

jobs:
  - name: migrate
    kind: PRE_DEPLOY
    github:
      repo: Dazzlin00/clyps
      branch: main
    dockerfile_path: Dockerfile
    instance_size_slug: basic-xxs
    instance_count: 1
    run_command: npm run migration:run:prod
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: DB_HOST
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_PORT
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_USERNAME
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_PASSWORD
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_DATABASE
        scope: RUN_AND_BUILD_TIME
        type: SECRET
